services:
  db:
    image: postgres:16.9-alpine3.20
    restart: always

    ports:
      - 5432:5432

    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
